name: pytorch_env
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - numpy
  - pandas
  - openpyxl
  - pytorch
  - pytorch-cuda=12.4
  - transformers
  - datasets
  - evaluate
  - scikit-learn
  - tqdm
  - tensorboard
  - accelerate