name: pytorch_env
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - numpy
  - pandas
  - openpyxl
  - pytorch
  - transformers
  - datasets
  - evaluate
  - scikit-learn
  - tqdm
  - tensorboard
  - accelerate
  - matplotlib

  - pip
  - pip:
      - torch --index-url https://download.pytorch.org/whl/cu128